//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Induction
    {
        public int InductionId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int ClientId { get; set; }
        public int InstructorId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual InductionStatu InductionStatu { get; set; }
        public virtual Instructor Instructor { get; set; }
    }
}
